# Generated by Django 4.0 on 2024-04-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevOpsStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('headline', models.CharField(max_length=200)),
                ('fees', models.IntegerField(verbose_name=10)),
                ('location', models.CharField(max_length=15)),
                ('number', models.IntegerField(verbose_name=11)),
            ],
        ),
    ]
